### ISSUE TITLE
파일: 코드 오류 4개 -> 실행 잘 됨

### ISSUE THREAD

**Issue by seojinJeon** [seojinJeon/next-chartjs#1]
> **VS Code**

<img width="376" alt="image" src="https://github.com/seojinJeon/next-chartjs/assets/127572801/078f7577-23ed-4f4b-a239-43e3b707ed77">

<div>
<img width="253" alt="image" src="https://github.com/seojinJeon/next-chartjs/assets/127572801/cf65d46e-c359-4fb0-a4db-ca089c4519dd">
</div>

<div>
<img width="173" alt="image" src="https://github.com/seojinJeon/next-chartjs/assets/127572801/0066b456-7c2f-469d-9335-2bac2072e974">
</div>

> **실행창**

<img width="455" alt="image" src="https://github.com/seojinJeon/next-chartjs/assets/127572801/6c4a7062-f276-405a-b967-a39a3df7e845">

<img width="381" alt="image" src="https://github.com/seojinJeon/next-chartjs/assets/127572801/c884eee6-0c5a-4a55-af2a-fc8caca11f3a">

<img width="370" alt="image" src="https://github.com/seojinJeon/next-chartjs/assets/127572801/2a70008e-606e-4644-88d3-2c39ac221ac9">

<img width="355" alt="image" src="https://github.com/seojinJeon/next-chartjs/assets/127572801/42178802-b6e3-4ea3-b755-9cca7e69d838">

> **참고영상**

https://www.youtube.com/watch?feature=shared&v=I-RdS_NSnak

**Comment by hyuckkim** [comment]
```typescript
  const chartRef = useRef<ElementRef<"canvas">>(null);
```
우선 generic으로 타입을 지정해줬습니다


```typescript
      if (chartRef.current.chart) {
        chartRef.current.chart.destroy();
      }
```
 => 삭제.


```typescript
      const context = chartRef.current.getContext("2d");
      if (!context) return;
```
타입 가드를 넣어줍니다


```typescript
      chartRef.current.chart = newChart;
```
=> 아래로 교체
```typescript
      return () => {
        newChart.destroy();
      }
```
(새로 useEffect가 실행되면 그 직전에 newChart.destroy가 실행됩니다!)

[stackoverflow](https://stackoverflow.com/questions/68100325)

이렇게 하면 제 환경 기준으로 오류는 안 보이고 차트도 잘 나오네요
